services:
  ibm_websphere:
    image: 'ibmcom/websphere-configured-no-jmx:0.1'
    #hostname: 'ibm_websphere'
    ports:
      - "9043:9043"
      - "9443:9443"
      - "7777:7777"
      - "1099:1099"
      - "9080:9080"
    volumes:
      - 'ibm_websphere_volume:/opt'
    networks:
      custom_net:
        ipv4_address: 10.5.0.5

#  ibm_db2:
#    image: 'ibmcom/db2:latest'
#    hostname: 'ibm_db2'
#    privileged: true
#    environment:
#      - 'DBNAME=mydb2'
#      - 'DB2INST1_PASSWORD=Password1'
#      - 'LICENSE=accept'
#    ports:
#      - '50000:50000'
#    volumes:
#      - 'ibm_db2_volume:/database'
#   networks:
#    custom_net:
#      ipv4_address: 10.5.0.7

  postgres:
    image: 'postgres:latest'
    hostname: 'postgres'
    environment:
      - 'POSTGRES_DB=memory_leak'
      - 'POSTGRES_PASSWORD=Password1'
      - 'POSTGRES_USER=nabbasi'
    volumes:
      - 'postgres_dev:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    networks:
      custom_net:
        ipv4_address: 10.5.0.7

  redis:
    image: "redis/redis-stack:latest"
    hostname: 'redis_stack'
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - 'REDIS_REPLICATION_MODE=master'
    networks:
      custom_net:
        ipv4_address: 10.5.0.8

volumes:
  ibm_websphere_volume:
  postgres_dev:
  ibm_db2_volume:

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1