services:
  ibm_websphere:
    image: 'ibmcom/websphere-traditional:latest'
    ports:
      - "9043:9043"
      - "9443:9443"
      - "7777:7777"
      - "1099:1099"
    volumes:
      - 'ibm_websphere_volume:/opt'

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=memory_leak'
      - 'POSTGRES_PASSWORD=Password1'
      - 'POSTGRES_USER=nabbasi'
    volumes:
      - 'postgres_dev:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  redis:
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  postgres_dev:
  ibm_websphere_volume:

networks:
  ibm_was_network:
    name: ibm_was_network
    external: true