#Disabling the Log4jContextSelector threads are releasing after 5 or 10 mins
Log4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector
log4j2.asyncLoggerRingBufferSize=4096
log4j2.asyncLoggerConfigRingBufferSize=4096
#log4j2.asyncLoggerWaitStrategy=Sleep
#log4j2.asyncLoggerWaitStrategy=YIELD
log4j2.disable.jmx=true
#log4j2.enable.threadlocals=false
log4j2.garbagefree.threadContextMap=true
log4j2.shutdownHookEnabled=true