server.port = 9092
server.servlet.context-path=/spring-boot-2-7-16-log4j-sync

spring.application.name=@name@

application.name=@name@
application.version=@version@
application.absher-classification = 1